from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(185, 185, 185);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 75))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 255, 0);\n"
                                 "color: rgb(85, 0, 0);")
        self.label.setObjectName("label")
        self.btm_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btm_equal.setGeometry(QtCore.QRect(300, 530, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_equal.setFont(font)
        self.btm_equal.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_equal.setObjectName("btm_equal")
        self.btm_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btm_0.setGeometry(QtCore.QRect(50, 520, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_0.setFont(font)
        self.btm_0.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_0.setObjectName("btm_0")
        self.btm_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btm_1.setGeometry(QtCore.QRect(0, 460, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_1.setFont(font)
        self.btm_1.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_1.setObjectName("btm_1")
        self.btm_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btm_2.setGeometry(QtCore.QRect(90, 460, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_2.setFont(font)
        self.btm_2.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_2.setObjectName("btm_2")
        self.btm_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btm_3.setGeometry(QtCore.QRect(180, 460, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_3.setFont(font)
        self.btm_3.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_3.setObjectName("btm_3")
        self.btm_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btm_4.setGeometry(QtCore.QRect(0, 400, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_4.setFont(font)
        self.btm_4.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_4.setObjectName("btm_4")
        self.btm_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btm_5.setGeometry(QtCore.QRect(90, 400, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_5.setFont(font)
        self.btm_5.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_5.setObjectName("btm_5")
        self.btm_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btm_6.setGeometry(QtCore.QRect(180, 400, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_6.setFont(font)
        self.btm_6.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_6.setObjectName("btm_6")
        self.btm_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btm_7.setGeometry(QtCore.QRect(0, 340, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_7.setFont(font)
        self.btm_7.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_7.setObjectName("btm_7")
        self.btm_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btm_9.setGeometry(QtCore.QRect(180, 340, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_9.setFont(font)
        self.btm_9.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_9.setObjectName("btm_9")
        self.btm_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btm_8.setGeometry(QtCore.QRect(90, 340, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_8.setFont(font)
        self.btm_8.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_8.setObjectName("btm_8")
        self.btm_sum = QtWidgets.QPushButton(self.centralwidget)
        self.btm_sum.setGeometry(QtCore.QRect(300, 460, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_sum.setFont(font)
        self.btm_sum.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_sum.setObjectName("btm_sum")
        self.btm_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btm_minus.setGeometry(QtCore.QRect(300, 400, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_minus.setFont(font)
        self.btm_minus.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_minus.setObjectName("btm_minus")
        self.btm_multi = QtWidgets.QPushButton(self.centralwidget)
        self.btm_multi.setGeometry(QtCore.QRect(300, 340, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_multi.setFont(font)
        self.btm_multi.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_multi.setObjectName("btm_multi")
        self.btm_delit = QtWidgets.QPushButton(self.centralwidget)
        self.btm_delit.setGeometry(QtCore.QRect(300, 280, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btm_delit.setFont(font)
        self.btm_delit.setStyleSheet("background-color: rgb(255, 165, 251);")
        self.btm_delit.setObjectName("btm_delit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Connect variables
        self.add_func()
        self.is_equal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "0"))
        self.btm_equal.setText(_translate("MainWindow", "="))
        self.btm_0.setText(_translate("MainWindow", "0"))
        self.btm_1.setText(_translate("MainWindow", "1"))
        self.btm_2.setText(_translate("MainWindow", "2"))
        self.btm_3.setText(_translate("MainWindow", "3"))
        self.btm_4.setText(_translate("MainWindow", "4"))
        self.btm_5.setText(_translate("MainWindow", "5"))
        self.btm_6.setText(_translate("MainWindow", "6"))
        self.btm_7.setText(_translate("MainWindow", "7"))
        self.btm_9.setText(_translate("MainWindow", "9"))
        self.btm_8.setText(_translate("MainWindow", "8"))
        self.btm_sum.setText(_translate("MainWindow", "+"))
        self.btm_minus.setText(_translate("MainWindow", "-"))
        self.btm_multi.setText(_translate("MainWindow", "*"))
        self.btm_delit.setText(_translate("MainWindow", "/"))

    def add_func(self):
        self.btm_0.clicked.connect(lambda: self.write_number(self.btm_0.text()))
        self.btm_1.clicked.connect(lambda: self.write_number(self.btm_1.text()))
        self.btm_2.clicked.connect(lambda: self.write_number(self.btm_2.text()))
        self.btm_3.clicked.connect(lambda: self.write_number(self.btm_3.text()))
        self.btm_4.clicked.connect(lambda: self.write_number(self.btm_4.text()))
        self.btm_5.clicked.connect(lambda: self.write_number(self.btm_5.text()))
        self.btm_6.clicked.connect(lambda: self.write_number(self.btm_6.text()))
        self.btm_7.clicked.connect(lambda: self.write_number(self.btm_7.text()))
        self.btm_8.clicked.connect(lambda: self.write_number(self.btm_8.text()))
        self.btm_9.clicked.connect(lambda: self.write_number(self.btm_9.text()))
        self.btm_sum.clicked.connect(lambda: self.write_number(self.btm_sum.text()))
        self.btm_minus.clicked.connect(lambda: self.write_number(self.btm_minus.text()))
        self.btm_multi.clicked.connect(lambda: self.write_number(self.btm_multi.text()))
        self.btm_delit.clicked.connect(lambda: self.write_number(self.btm_delit.text()))

        self.btm_equal.clicked.connect(self.result)

    def write_number(self, number):
        if self.label.text() == '0' or self.is_equal:
            self.label.setText(number)
            self.is_equal = False
        else:
            self.label.setText(self.label.text() + number)

    def result(self):
        res = eval(self.label.text())
        self.label.setText("= " + str(res))
        self.is_equal = True


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
